version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "${PORT_BACK}:${PORT_BACK}"
    env_file:
      - .env
    environment:
      - PORT_BACK
      - URL_FRONT
      - JWT_SECRET
      - JWT_SECRET_CLIENT
      - NODE_ENV
      - ACCESS_TOKEN_MERCADO_PAGO
      - CONNECTION_LIMIT
      - HOST
      - USER
      - PASSWORD
      - DATABASE
    depends_on:
      - mysql
    networks:
      - network_public
      - internal

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_BASE_URL_BACK: ${REACT_APP_BASE_URL_BACK}
        REACT_APP_BASE_URL_FRONT: ${REACT_APP_BASE_URL_FRONT}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - network_public

  mysql:
    image: mysql:8.0
    container_name: comanda_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal

volumes:
  mysql_data:

networks:
  network_public:
    external: true
    name: network_public

  internal:
    driver: bridge
