version: "3.8"

services:
  backend:
    image: jackssads/comanda_back:1.0
    environment:
      - PORT_BACK=3001
      - URL_FRONT=https://example.com
      - JWT_SECRET=developer
      - JWT_SECRET_CLIENT=client
      - NODE_ENV=production
      - ACCESS_TOKEN_MERCADO_PAGO=
      - CONNECTION_LIMIT=10
      - HOST=mysql
      - USER=root
      - PASSWORD=123
      - DATABASE=comanda_menu
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

    networks:
      - network_public
    ports:
      - "3001:3001"

  frontend:
    image: jackssads/comanda_front:1.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    labels:
      - traefik.enable=true"
      - traefik.http.routers.frontend.rule=Host(https://example.com)
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.tls=true
      - traefik.http.routers.frontend.tls.certresolver=letsencryptresolver
      - traefik.http.services.frontend.loadbalancer.server.port=3000

    depends_on:
      - backend
    networks:
      - network_public
    ports:
      - "3000:3000"

volumes:
  mysql_data:

networks:
  network_public:
    external: true
    name: network_public
